dataSources:
  ds_1: # 数据源名称
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://116.198.253.55:3306/db_user
    username: root
    password: gong990117
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://116.198.253.55:3306/db_order
    username: root
    password: gong990117

rules:
  - !SHARDING
    tables: # 数据分片规则配置
      t_user: # 逻辑表名称
        actualDataNodes: ds_1.t_user
      t_order: # 逻辑表名称
        actualDataNodes: ds_2.t_order

# 打印SQL
props:
  sql-show: true


#  # 标准分片表配置（数据节点）
#  # spring.shardingsphere.rules.sharding.tables.<table-name>.actual-data-nodes=值
#  # 值由数据源名 + 表名组成，以小数点分隔。
#  # <table-name>：逻辑表名
#spring.shardingsphere.rules.sharding.tables.t_user.actual-data-nodes=server-user.t_user
#spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=server-order.t_order
#
#
#  # 打印SQL
#spring.shardingsphere.props.sql-show=true